/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IPRegistry {
  export type IPAssetStruct = {
    id: BigNumberish;
    ipfsHash: string;
    owner: AddressLike;
    assetType: string;
    timestamp: BigNumberish;
  };

  export type IPAssetStructOutput = [
    id: bigint,
    ipfsHash: string,
    owner: string,
    assetType: string,
    timestamp: bigint
  ] & {
    id: bigint;
    ipfsHash: string;
    owner: string;
    assetType: string;
    timestamp: bigint;
  };
}

export interface IPRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetLicenses"
      | "getAsset"
      | "getAssetsByOwner"
      | "getCertificate"
      | "getLicense"
      | "owner"
      | "registerAsset"
      | "renounceOwnership"
      | "setLicense"
      | "totalAssets"
      | "transferAsset"
      | "transferOwnership"
      | "verifyAsset"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetRegistered"
      | "AssetTransferred"
      | "LicenseSet"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assetLicenses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLicense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLicense",
    values: [BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAsset",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifyAsset", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "assetLicenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLicense", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLicense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAsset",
    data: BytesLike
  ): Result;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    ipfsHash: string,
    assetType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    owner: string,
    ipfsHash: string,
    assetType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    owner: string;
    ipfsHash: string;
    assetType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetTransferredEvent {
  export type InputTuple = [
    assetId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assetId: bigint,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    assetId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseSetEvent {
  export type InputTuple = [
    assetId: BigNumberish,
    price: BigNumberish,
    isCommercial: boolean,
    royaltyPercent: BigNumberish
  ];
  export type OutputTuple = [
    assetId: bigint,
    price: bigint,
    isCommercial: boolean,
    royaltyPercent: bigint
  ];
  export interface OutputObject {
    assetId: bigint;
    price: bigint;
    isCommercial: boolean;
    royaltyPercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetLicenses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, bigint] & {
        price: bigint;
        isCommercial: boolean;
        royaltyPercent: bigint;
      }
    ],
    "view"
  >;

  getAsset: TypedContractMethod<
    [_id: BigNumberish],
    [IPRegistry.IPAssetStructOutput],
    "view"
  >;

  getAssetsByOwner: TypedContractMethod<
    [_owner: AddressLike],
    [bigint[]],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [_id: BigNumberish],
    [
      [bigint, string, string, string, bigint, string] & {
        id: bigint;
        owner: string;
        ipfsHash: string;
        assetType: string;
        timestamp: bigint;
        onChainLink: string;
      }
    ],
    "view"
  >;

  getLicense: TypedContractMethod<
    [_assetId: BigNumberish],
    [
      [bigint, boolean, bigint] & {
        price: bigint;
        isCommercial: boolean;
        royaltyPercent: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAsset: TypedContractMethod<
    [_ipfsHash: string, _assetType: string],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setLicense: TypedContractMethod<
    [
      _assetId: BigNumberish,
      _price: BigNumberish,
      _isCommercial: boolean,
      _royaltyPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  transferAsset: TypedContractMethod<
    [_assetId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyAsset: TypedContractMethod<
    [_ipfsHash: string],
    [
      [boolean, bigint, string, bigint, string] & {
        exists: boolean;
        assetId: bigint;
        owner: string;
        timestamp: bigint;
        assetType: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetLicenses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, boolean, bigint] & {
        price: bigint;
        isCommercial: boolean;
        royaltyPercent: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [IPRegistry.IPAssetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAssetsByOwner"
  ): TypedContractMethod<[_owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [bigint, string, string, string, bigint, string] & {
        id: bigint;
        owner: string;
        ipfsHash: string;
        assetType: string;
        timestamp: bigint;
        onChainLink: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLicense"
  ): TypedContractMethod<
    [_assetId: BigNumberish],
    [
      [bigint, boolean, bigint] & {
        price: bigint;
        isCommercial: boolean;
        royaltyPercent: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [_ipfsHash: string, _assetType: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLicense"
  ): TypedContractMethod<
    [
      _assetId: BigNumberish,
      _price: BigNumberish,
      _isCommercial: boolean,
      _royaltyPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAsset"
  ): TypedContractMethod<
    [_assetId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyAsset"
  ): TypedContractMethod<
    [_ipfsHash: string],
    [
      [boolean, bigint, string, bigint, string] & {
        exists: boolean;
        assetId: bigint;
        owner: string;
        timestamp: bigint;
        assetType: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AssetTransferred"
  ): TypedContractEvent<
    AssetTransferredEvent.InputTuple,
    AssetTransferredEvent.OutputTuple,
    AssetTransferredEvent.OutputObject
  >;
  getEvent(
    key: "LicenseSet"
  ): TypedContractEvent<
    LicenseSetEvent.InputTuple,
    LicenseSetEvent.OutputTuple,
    LicenseSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AssetRegistered(uint256,address,string,string,uint256)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "AssetTransferred(uint256,address,address,uint256)": TypedContractEvent<
      AssetTransferredEvent.InputTuple,
      AssetTransferredEvent.OutputTuple,
      AssetTransferredEvent.OutputObject
    >;
    AssetTransferred: TypedContractEvent<
      AssetTransferredEvent.InputTuple,
      AssetTransferredEvent.OutputTuple,
      AssetTransferredEvent.OutputObject
    >;

    "LicenseSet(uint256,uint256,bool,uint256)": TypedContractEvent<
      LicenseSetEvent.InputTuple,
      LicenseSetEvent.OutputTuple,
      LicenseSetEvent.OutputObject
    >;
    LicenseSet: TypedContractEvent<
      LicenseSetEvent.InputTuple,
      LicenseSetEvent.OutputTuple,
      LicenseSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
